//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Appointments = new HashSet<Appointment>();
            this.AppointmentShareToUsers = new HashSet<AppointmentShareToUser>();
            this.AccessableAttachments = new HashSet<AttachmentAccount>();
            this.UploadedAttachments = new HashSet<Attachment>();
            this.SentMessages = new HashSet<ChatMessage>();
            this.ReceivedMessages = new HashSet<ChatMessage>();
            this.Courses = new HashSet<Course>();
            this.Friendships = new HashSet<Friendship>();
            this.Friendships1 = new HashSet<Friendship>();
            this.BelongtoGroups = new HashSet<GroupMember>();
            this.Groups = new HashSet<Group>();
            this.SelectableCourses = new HashSet<SelectableCourseStudent>();
        }
    
        public long Id { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string Email { get; set; }
        public string WeChatOpenId { get; set; }
        public string EncryptedPassword { get; set; }
        public string PasswordSalt { get; set; }
        public byte Gender { get; set; }
        public byte UserType { get; set; }
        public bool IsAdmin { get; set; }
        public string HeadImgUrl { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<long> ClassId { get; set; }
        public string SchoolCardNum { get; set; }
        public System.DateTime RegistionTime { get; set; }
        public Nullable<System.DateTime> ThisLoginTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string ThisLoginIP { get; set; }
        public string LastLoginIP { get; set; }
    
        public virtual ClassInfo Class { get; set; }
        public virtual SchoolInfo School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentShareToUser> AppointmentShareToUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentAccount> AccessableAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> UploadedAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessage> SentMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessage> ReceivedMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friendship> Friendships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friendship> Friendships1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMember> BelongtoGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectableCourseStudent> SelectableCourses { get; set; }
    }
}
