//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Appointments = new HashSet<Appointment>();
            this.FriendAppointments = new HashSet<AppointmentShare>();
            this.GrantedAttachment = new HashSet<AttachmentAccess>();
            this.SentAttachments = new HashSet<Attachment>();
            this.SentMessages = new HashSet<ChatMessage>();
            this.ReceivedMessages = new HashSet<ChatMessage>();
            this.Teacher_Courses = new HashSet<Course>();
            this.SentFriendRequests = new HashSet<Friendship>();
            this.ReceivedFriendRequests = new HashSet<Friendship>();
            this.ManagesGroups = new HashSet<Group>();
            this.SentNotifications = new HashSet<Notification>();
            this.ReceivedNotifications = new HashSet<Notification>();
        }
    
        public long Id { get; set; }
        public string UserName { get; set; }
        public string EncryptedPassword { get; set; }
        public string PasswordSalt { get; set; }
        public byte Gender { get; set; }
        public string Email { get; set; }
        public bool EmailPresent { get; set; }
        public string WeChatOpenId { get; set; }
        public bool WeChatOpenIdPresent { get; set; }
        public byte UserType { get; set; }
        public bool IsAdmin { get; set; }
        public string RealName { get; set; }
        public string HeadImg { get; set; }
        public Nullable<long> SchoolId { get; set; }
        public Nullable<long> ClassId { get; set; }
        public Nullable<long> Major { get; set; }
        public string SchoolCardNum { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public System.DateTime ThisLoginTime { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string ThisLoginIP { get; set; }
        public string LastLoginIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentShare> FriendAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentAccess> GrantedAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> SentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessage> SentMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessage> ReceivedMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Teacher_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friendship> SentFriendRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friendship> ReceivedFriendRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> ManagesGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> SentNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> ReceivedNotifications { get; set; }
        public virtual Group School { get; set; }
        public virtual Group Class { get; set; }
    }
}
