//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Shares = new HashSet<AppointmentShareToUser>();
            this.Classes = new HashSet<ClassInfo>();
            this.Groups = new HashSet<Group>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public long CreatorId { get; set; }
        public string Details { get; set; }
        public string Place { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public bool IsAllDay { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public byte Visibily { get; set; }
    
        public virtual Account Creator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentShareToUser> Shares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassInfo> Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
    }
}
