//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.AppointmentShares = new HashSet<AppointmentShare>();
        }
    
        public long Id { get; set; }
        public long CreaterUserId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public System.DateTime StartTime { get; set; }
        public bool IsAllDay { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Place { get; set; }
        public System.DateTime CreationTime { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual Account Creater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentShare> AppointmentShares { get; set; }
    }
}
