//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentCourse
    {
        public long AttachmentId { get; set; }
        public long CourseId { get; set; }
        public System.DateTime CourseTime { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual Course Course { get; set; }
    }
}
