//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attachment()
        {
            this.Accounts = new HashSet<AttachmentAccount>();
            this.Classes = new HashSet<AttachmentClass>();
            this.Courses = new HashSet<AttachmentCourse>();
            this.Groups = new HashSet<AttachmentGroup>();
        }
    
        public long Id { get; set; }
        public string StoragePath { get; set; }
        public string FileName { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string MD5Hash { get; set; }
        public bool IsPublicAttachment { get; set; }
        public long UploaderId { get; set; }
        public System.DateTime UploadTime { get; set; }
        public System.DateTime ExpireTime { get; set; }
    
        public virtual Account Uploader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentAccount> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentClass> Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentCourse> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentGroup> Groups { get; set; }
    }
}
