//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentAccess
    {
        public long AttachmentId { get; set; }
        public Nullable<long> AccessorId { get; set; }
        public bool IsGroup { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Attachment Attachment { get; set; }
        public virtual Group Group { get; set; }
    }
}
