//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public byte MessageType { get; set; }
        public string MessageContent { get; set; }
        public long SenderId { get; set; }
        public long ReceiverId { get; set; }
        public bool IsSendToGroup { get; set; }
        public System.DateTime SendTime { get; set; }
    
        public virtual Account Sender { get; set; }
        public virtual Account Receiver { get; set; }
        public virtual Group Group { get; set; }
    }
}
