//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.AttachmentCourses = new HashSet<AttachmentCourse>();
            this.CourseChanges = new HashSet<CourseChange>();
            this.CourseTimes = new HashSet<CourseTime>();
            this.Classes = new HashSet<ClassInfo>();
            this.SelectedUsers = new HashSet<Account>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public long TeacherId { get; set; }
        public int SchoolId { get; set; }
        public bool IsSelectableCourse { get; set; }
        public System.DateTime SemesterStart { get; set; }
        public byte[] Weeks { get; set; }
    
        public virtual Account Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentCourse> AttachmentCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseChange> CourseChanges { get; set; }
        public virtual SchoolInfo School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTime> CourseTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassInfo> Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> SelectedUsers { get; set; }
    }
}
