//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public long GroupId { get; set; }
        public long MemberId { get; set; }
        public bool IsAccepted { get; set; }
    
        public virtual Account Member { get; set; }
        public virtual Group Group { get; set; }
    }
}
