//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILeafEntities : DbContext
    {
        public ILeafEntities()
            : base("name=ILeafEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentShareToUser> AppointmentShareToUsers { get; set; }
        public virtual DbSet<AttachmentAccount> AttachmentAccounts { get; set; }
        public virtual DbSet<AttachmentClass> AttachmentClasses { get; set; }
        public virtual DbSet<AttachmentCourse> AttachmentCourses { get; set; }
        public virtual DbSet<AttachmentGroup> AttachmentGroups { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<ClassAppointment> ClassAppointments { get; set; }
        public virtual DbSet<ClassInfo> ClassInfos { get; set; }
        public virtual DbSet<CourseChange> CourseChanges1 { get; set; }
        public virtual DbSet<CourseClass> CourseClasses { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseTime> CourseTimes { get; set; }
        public virtual DbSet<Friendship> Friendships { get; set; }
        public virtual DbSet<GroupAppointment> GroupAppointments { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<SchoolInfo> SchoolInfos { get; set; }
        public virtual DbSet<SelectableCourseStudent> SelectableCourseStudents { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
