//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILeaf.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public System.DateTime SentTime { get; set; }
        public Nullable<long> SenderId { get; set; }
        public long RecipientId { get; set; }
        public long GroupId { get; set; }
    
        public virtual Account Sender { get; set; }
        public virtual Account Recipient { get; set; }
        public virtual Group Group { get; set; }
    }
}
